services:
  - type: web
    name: lgm-dubai
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    branch: main
