services:
  - type: web
    name: lgm-dubai
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
      - key: ESLINT_NO_DEV_ERRORS
        value: true
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    healthCheckPath: /
    autoDeploy: true
    branch: main
